version: "3"

services:
  doc:
    image: jameszbl/authmore-doc
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - authmore-doc
    ports:
      - "3001:80"

networks:
  authmore-doc:
